[build]
  publish = "public"

[[redirects]]
  from = "https://alexperronnet.com"
  to = "https://alexperronnet.io"
  status = 301

[[redirects]]
  from = "https://www.alexperronnet.com"
  to = "https://alexperronnet.io"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"